### ISSUE TITLE
Define versioning

### ISSUE THREAD

**Issue by tjanez** [oasisprotocol/oasis-core-ledger#21]
Since the signer plugin needs to be rebuilt with the exact version of Oasis Core, it probably makes sense to follow [Oasis Core's versioning](https://github.com/oasisprotocol/oasis-core/blob/master/docs/versioning.md) and perhaps use independent `.MICRO` versions (from `YY.MINOR[.MICRO]`).

**Comment by Yawning** [comment]
This is no longer true.  Old plugins will function with newer Oasis Core builds unless the version number (part of the plugin initialization handshake) breaks.

That said, we should probably add `--version` to the plugin binary so that we can display version information (so that we can tell people to upgrade if we fix the plugin itself).
